---
driver:
  name: vagrant
  provider: parallels
  customize:
    memory: 8192
    cpus: 2

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: apex/macos-10.13
    driver:
      box: apex/macos-10.13
      box_url: http://imagr.corp.microsoft.com:8099/apex/macos-10.13
      box_check_update: true

suites:
  - name: default
    run_list:
      - recipe[macos::ard]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
